# Generated by Django 3.1.4 on 2021-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(default='', max_length=100, verbose_name='주문상품'),
        ),
    ]
