# Generated by Django 3.1.4 on 2021-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210117_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
