# Generated by Django 3.1.4 on 2021-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20210117_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_requset',
            field=models.TextField(default=''),
        ),
    ]
