# Generated by Django 3.1.4 on 2021-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_order_order_requset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_date',)},
        ),
    ]
