# Generated by Django 3.1.4 on 2021-01-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20210117_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='shopping.product')),
            ],
            options={
                'ordering': ('-products',),
            },
        ),
    ]
